insert into users (username, password, profile_pic) values ('soldman0', 'IDBteo', 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into users (username, password, profile_pic) values ('obanger1', 'qx3SjmX', 'http://dummyimage.com/100x100.jpg/cc0000/ffffff');
insert into users (username, password, profile_pic) values ('crentcome2', 'NpiKJpMl6', 'http://dummyimage.com/100x100.jpg/dddddd/000000');
insert into users (username, password, profile_pic) values ('adolphin3', 'I5cKYt7i', 'http://dummyimage.com/100x100.bmp/dddddd/000000');
insert into users (username, password, profile_pic) values ('mmicallef4', 'ziNkWWFLlMw9', 'http://dummyimage.com/100x100.bmp/ff4444/ffffff');
insert into users (username, password, profile_pic) values ('zmyatt5', 'xIETFXw', 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into users (username, password, profile_pic) values ('ckemery6', 'K2ICWVA4j', 'http://dummyimage.com/100x100.jpg/ff4444/ffffff');
insert into users (username, password, profile_pic) values ('rmeddows7', 'GndE7YY', 'http://dummyimage.com/100x100.jpg/dddddd/000000');
insert into users (username, password, profile_pic) values ('fmcinility8', 'oiEe2G7AyDkZ', 'http://dummyimage.com/100x100.bmp/dddddd/000000');
insert into users (username, password, profile_pic) values ('kfransman9', '7AVrFMRhoa', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into users (username, password, profile_pic) values ('tshaftoa', 'QTejk37', 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into users (username, password, profile_pic) values ('ocorwinb', '6vkVx6gO5', 'http://dummyimage.com/100x100.jpg/5fa2dd/ffffff');
insert into users (username, password, profile_pic) values ('dcavanc', 'LlNP8PMNqNm', 'http://dummyimage.com/100x100.bmp/cc0000/ffffff');
insert into users (username, password, profile_pic) values ('lkirkhamd', 'sNhXzpsgjf', 'http://dummyimage.com/100x100.bmp/5fa2dd/ffffff');
insert into users (username, password, profile_pic) values ('pgoldbourne', 'tmLuZa0645d', 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into users (username, password, profile_pic) values ('rcoldicottf', 'BnRBgC', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into users (username, password, profile_pic) values ('klenouryg', '7ICPS6', 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into users (username, password, profile_pic) values ('gcornierh', 'DJRwaVNw6', 'http://dummyimage.com/100x100.bmp/ff4444/ffffff');
insert into users (username, password, profile_pic) values ('blewendoni', 'Cm1bC698', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into users (username, password, profile_pic) values ('vstearnej', 'fowLoSXYzg', 'http://dummyimage.com/100x100.jpg/dddddd/000000');
insert into users (username, password, profile_pic) values ('hskynnerk', 'lNhQtvw6', 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into users (username, password, profile_pic) values ('kgroomel', 'MxBvNOe00wZ', 'http://dummyimage.com/100x100.jpg/ff4444/ffffff');
insert into users (username, password, profile_pic) values ('lantonim', 'VTc3qhm49c', 'http://dummyimage.com/100x100.bmp/ff4444/ffffff');
insert into users (username, password, profile_pic) values ('ztelfordn', 'kHp11Zwrag', 'http://dummyimage.com/100x100.bmp/dddddd/000000');
insert into users (username, password, profile_pic) values ('bstatefieldo', 'gWXg5FqCP', 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into users (username, password, profile_pic) values ('ndorceyp', '9LxEyITPHen', 'http://dummyimage.com/100x100.bmp/dddddd/000000');
insert into users (username, password, profile_pic) values ('tstidworthyq', 'IA8JHWPPiaKR', 'http://dummyimage.com/100x100.bmp/cc0000/ffffff');
insert into users (username, password, profile_pic) values ('lvowdenr', 'NugsuXyLk', 'http://dummyimage.com/100x100.jpg/cc0000/ffffff');
insert into users (username, password, profile_pic) values ('mbarrells', 'VAP8CgE2', 'http://dummyimage.com/100x100.bmp/dddddd/000000');
insert into users (username, password, profile_pic) values ('kkolodziejt', '2x3TGw4', 'http://dummyimage.com/100x100.png/dddddd/000000');

insert into posts (title, img, content) values ('nGHDwcJl9vI', 'http://dummyimage.com/250x250.png/cc0000/ffffff', 'Exclusive homogeneous synergy');
insert into posts (title, img, content) values ('oXvZ5nbA4MT', 'http://dummyimage.com/250x250.jpg/5fa2dd/ffffff', 'Automated secondary functionalities');
insert into posts (title, img, content) values ('4YgCJYnUA04', 'http://dummyimage.com/250x250.jpg/dddddd/000000', 'Fundamental systematic complexity');
insert into posts (title, img, content) values ('i9GLUO4LRSy', 'http://dummyimage.com/250x250.jpg/ff4444/ffffff', 'Focused optimizing moratorium');
insert into posts (title, img, content) values ('iDmWpos8l1E', 'http://dummyimage.com/250x250.bmp/dddddd/000000', 'Decentralized 5th generation approach');
insert into posts (title, img, content) values ('l4vMISOWTsr', 'http://dummyimage.com/250x250.bmp/ff4444/ffffff', 'Mandatory demand-driven open system');
insert into posts (title, img, content) values ('9qI23DZyCM5', 'http://dummyimage.com/250x250.png/5fa2dd/ffffff', 'Synchronised static conglomeration');
insert into posts (title, img, content) values ('Xx75Sacpc6Q', 'http://dummyimage.com/250x250.jpg/cc0000/ffffff', 'Adaptive eco-centric firmware');
insert into posts (title, img, content) values ('fGKCkLqfiGj', 'http://dummyimage.com/250x250.png/dddddd/000000', 'User-centric upward-trending standardization');
insert into posts (title, img, content) values ('HjaCg8MUTKH', 'http://dummyimage.com/250x250.png/5fa2dd/ffffff', 'Reactive background intranet');
insert into posts (title, img, content) values ('vzBPxhAECos', 'http://dummyimage.com/250x250.jpg/dddddd/000000', 'Visionary 24 hour forecast');
insert into posts (title, img, content) values ('vgpCm7AoslR', 'http://dummyimage.com/250x250.jpg/5fa2dd/ffffff', 'Ergonomic multimedia function');
insert into posts (title, img, content) values ('FYu2WJWB1so', 'http://dummyimage.com/250x250.png/ff4444/ffffff', 'De-engineered maximized help-desk');
insert into posts (title, img, content) values ('xDV33X9tpYZ', 'http://dummyimage.com/250x250.bmp/ff4444/ffffff', 'Upgradable clear-thinking success');
insert into posts (title, img, content) values ('ZcN1tsBKUsG', 'http://dummyimage.com/250x250.bmp/dddddd/000000', 'Reduced local system engine');
insert into posts (title, img, content) values ('x8aDSM7tZvb', 'http://dummyimage.com/250x250.bmp/ff4444/ffffff', 'Ergonomic context-sensitive function');
insert into posts (title, img, content) values ('N3MN1J2Spji', 'http://dummyimage.com/250x250.bmp/dddddd/000000', 'Organic neutral extranet');
insert into posts (title, img, content) values ('QzyeFhBWYPh', 'http://dummyimage.com/250x250.jpg/ff4444/ffffff', 'Object-based 24 hour matrix');
insert into posts (title, img, content) values ('76y0X8c2hh3', 'http://dummyimage.com/250x250.png/cc0000/ffffff', 'Exclusive composite system engine');
insert into posts (title, img, content) values ('GZLrvREWulo', 'http://dummyimage.com/250x250.png/dddddd/000000', 'Adaptive full-range initiative');
insert into posts (title, img, content) values ('r2uKoYixXl4', 'http://dummyimage.com/250x250.png/dddddd/000000', 'Fully-configurable dynamic concept');
insert into posts (title, img, content) values ('XjiGdljlceE', 'http://dummyimage.com/250x250.jpg/5fa2dd/ffffff', 'Open-source global internet solution');
insert into posts (title, img, content) values ('kYKM9tc16hT', 'http://dummyimage.com/250x250.bmp/cc0000/ffffff', 'Inverse cohesive paradigm');
insert into posts (title, img, content) values ('HiLynJwXROF', 'http://dummyimage.com/250x250.png/5fa2dd/ffffff', 'Inverse bandwidth-monitored monitoring');
insert into posts (title, img, content) values ('Zf9QXTn6Dnw', 'http://dummyimage.com/250x250.bmp/5fa2dd/ffffff', 'Multi-lateral dynamic strategy');
insert into posts (title, img, content) values ('fPmTMEq9Djk', 'http://dummyimage.com/250x250.jpg/ff4444/ffffff', 'Face to face systematic synergy');
insert into posts (title, img, content) values ('51mgmkgPgKT', 'http://dummyimage.com/250x250.jpg/cc0000/ffffff', 'Operative didactic moderator');
insert into posts (title, img, content) values ('JYQB13iSC6y', 'http://dummyimage.com/250x250.bmp/cc0000/ffffff', 'Optional intangible infrastructure');
insert into posts (title, img, content) values ('07iwRf5GTnU', 'http://dummyimage.com/250x250.png/5fa2dd/ffffff', 'Total radical system engine');
insert into posts (title, img, content) values ('o6PNpQ5r3VM', 'http://dummyimage.com/250x250.bmp/ff4444/ffffff', 'Ameliorated directional data-warehouse');
